### ISSUE TITLE
WBPaper00051279 missing in TPC

### ISSUE THREAD

**Issue by draciti** [WormBase/textpresso#114]

**Comment by draciti** [comment]
it's actually there, it did not retrieve it as there was still WBPaper00051279 in the main search box, that was probably overriding the 'Additional Search Option' query. Is this is how it is supposed to work?

**Comment by chris-grove** [comment]
@draciti 
Do you mean you had "WBPaper00051279" in the main search box of the Textpresso Central page header and/or in the "Keywords" search box on the "Search" tab?

If that's the case, then you're likely not ever going to get any hits, because there are no papers that refer to "WBPaper00051279" inside the text of the paper. You would just need to put it in the "Accession" field of the "Additional Search Options" box, leave the main search box empty, and run the search.

**Comment by draciti** [comment]
yes Chris, that's what I have experienced.
We can discuss it at the next TP meeting alongside the curation tab capabilities.
Living this open until then
thanks!
