### ISSUE TITLE
Search result page crashes when using complex Boolean queries.

### ISSUE THREAD

**Issue by goldturtle** [WormBase/textpresso#117]
When searching for DYN-1 AND (mitosis OR meiosis), search results appear, but when you click on title panel, system crashes.

**Comment by valearna** [comment]
The problem was located in the function than highlights the matching keywords in the text and was related to the presence of the parentheses. We fixed the bug by removing the parentheses from the keywords when used for highlighting the text. We also updated the viewer page with the new highlighting scheme.
