### ISSUE TITLE
TPC search returning wrong paper

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#122]
I found something strange:

When I query only for the paper WBPaper00050796, I get that correct paper returned. When I do a sentence level search looking for three categories to match each sentence (keeping the paper accession the same "WBPaper00050796") and perform the search I get a completely different paper. Here's a screen recording:

https://www.dropbox.com/s/dzn73e6ytzk1qpx/TPC_search_returning_wrong_paper_Feb_26_2018.mov?dl=0

**Comment by chris-grove** [comment]
It seems that as soon as I turn on the Sentence scope AND add a category, I get the wrong paper(s) returned in the search results. This happens consistently on Firefox, Chrome, and Safari

**Comment by valearna** [comment]
It seems that the problem is related to corrupted index data. We found multiple bugs in the indexer code and we are currently re-generating the index from scratch. I tested the queries in your screen recording on the new index and they return the correct results. The indexing process for the new version is at 50% and it will take another couple of days before we can deploy it. I will notify you as soon as the new version is ready.

**Comment by chris-grove** [comment]
@valearna 
OK, thanks!

**Comment by valearna** [comment]
I've just linked the new index and tested the search that was returning wrong results. Everything seems to work.

**Comment by chris-grove** [comment]
@valearna 
Looks good! Thanks! Closing.
