### ISSUE TITLE
C. elegans TPC search returning wrong paper

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/textpresso#127]
Hi,

I just performed a keyword search (basis AND unknown) on the C. elegans corpus, sorted by year, and the results returned at least one incorrect match.

I received matches in PMID:25353777 (page 3) that actually correspond to text in PMID:29030550 (page 1).

The text in PMID:29030550 is correctly returned.

**Comment by valearna** [comment]
Hi Kimberly, I think I found the problem, but I need more details to understand what's wrong. I performed the same search but I didn't find PMID:25353777 on page 3 but a similar ID: PMID:25373777. Is this the paper that is giving you wrong text? When I open the panel from the search interface for that paper I see a wrong matching sentence, which is indeed related to paper PMID:29030550, but the abstract is correct and if I open the paper in the viewer I get the right text for PMID:25353777. Thus, the problem seems to be related only to the matching sentences. Can you please confirm this?

**Comment by vanaukenk** [comment]
Hi @valearna 
Thanks for your quick response.  Yes, the paper ID on page three should be:  PMID:25373777
Apologies for the typo.
The correct papers are presented in the paper viewer for each paper, but the correct matching sentence for PMID:25373777 is not highlighted.
Please let me know if you need any additional info.

**Comment by valearna** [comment]
Ok, thanks. I've found the bug and updated the website. I tested it with the same keyword search and the new results look good to me. Can you please try some additional searches and let me know if everything is ok?

**Comment by vanaukenk** [comment]
Thanks, @valearna 
I just tried a new keyword search, "ne12", on the C. elegans corpus and got nine papers, but the results page for a document search looked like this:
![ne12_search_results](https://user-images.githubusercontent.com/1730534/38436743-741923c4-39a3-11e8-9e74-64b9fe1efe7b.png)
The sentence-level search results look fine.
I see the same behavior (i.e. document vs sentence search) for another keyword search: "cell AND migration AND Wnt"

**Comment by valearna** [comment]
Thanks @vanaukenk for testing. My edit to the sentence searches affected a state variable in the document searches. Everything should be ok now.

**Comment by vanaukenk** [comment]
Thanks @valearna 
All seems to be working fine now.
