### ISSUE TITLE
Labeling supplemental documents in search results

### ISSUE THREAD

**Issue by chris-grove** [WormBase/textpresso#128]
If I perform a search for WBPaper00050382 in TPC using the additional search options, and I'm not logged in to TPC, I get 11 documents that match, the first 10 of which are scored 100 and refer to supplemental figures but all appear to refer to the same supplemental document. The 11th match that is displayed is the actual main paper, is scored 0:

https://www.dropbox.com/s/b2wm5a57iovs9e8/TPC_11_documents_for_same_paper_May_21_2018.mov?dl=0

What is strange is that if I am logged in I only get one document returned which appears to be the main document for the paper with the supplemental material merged into the same document.

Is there a reason (legal copyright issues?) for returning separate documents when not logged in and a single merged document when logged in? I think it would ultimately be much more convenient if all the documents were merged into a single doc in both cases.

**Comment by valearna** [comment]
This is the default behavior in textpresso since supplemental material is indexed as separate documents with the same bibliographic information as the main paper. The difference in score is due to the our normalization: the initial score is assigned by lucene based on the search criteria. In this case both supplemental material and the main paper have a match but their score differ (probably by a very small factor). Then we normalize the scores and make them between 0 and 100, where 0 is assigned to the doc with the smallest returned score and 100 to the highest. 

The difference between the search performed when you are logged out/in may be due to the selection of literature entries. Are you including the "C. elegans supplementals" literature from the "select literature" dialog when you are logged in?

I don't know if all the pdfs in WormBase are merged with their supplemental material. This may be a special case, but @goldturtle can probably give you more details.

**Comment by chris-grove** [comment]
@valearna 
OK, yes, you're right: the discrepancy between being logged in or not was the selected literature.

Would it be possible to indicate somewhere in the results showing each distinct supplemental document what the name of the supplemental document is? As of now, they are completely indistinguishable until you open them up. I know that in many cases the original source names are coded and not human-readable, but they are, I think, always unique. If they are human readable (as the supplemental docs are for WBPaper00050382 on Tazendra) then great, otherwise if they preserved the original supplemental document names from the source, then people could at least cross check the names of the documents with the source.

**Comment by chris-grove** [comment]
@valearna 
Also, whether PDFs are merged into a single document or not is hit or miss. In this case, the providers of the files happened to merge supplementals with the main paper document, but then also provide supplementals individually. It may depend on the publisher or other factors.

**Comment by valearna** [comment]
Sure, I will look into the code of the script that gets bib info for the papers from tazendra and see if we can have more representative titles. Do you think that marking the title with "Supplemental material", maybe in parentheses, would help?

**Comment by chris-grove** [comment]
@valearna 
Yes, I think that would help. Once expanded open, you can see that it is labeled in the "Literature" field as "C. elegans Supplementals", but there is no further name or description of the file to allow a user to discern which supplemental document it is without viewing the document itself.

**Comment by valearna** [comment]
Ok, thanks @chris-grove I'll add it to the title.

**Comment by goldturtle** [comment]
Seems to be resolved.
